const lightTheme = {
    colors: {
        primary: "#3B608F",
        surfaceTint: "#3B608F",
        onPrimary: "#FFFFFF",
        primaryContainer: "#D4E3FF",
        onPrimaryContainer: "#204876",
        secondary: "#056B5C",
        onSecondary: "#FFFFFF",
        secondaryContainer: "#A0F2DE",
        onSecondaryContainer: "#005145",
        tertiary: "#6B538C",
        onTertiary: "#FFFFFF",
        tertiaryContainer: "#EDDCFF",
        onTertiaryContainer: "#533C72",
        error: "#BA1A1A",
        onError: "#FFFFFF",
        errorContainer: "#FFDAD6",
        onErrorContainer: "#93000A",
        background: "#F8F9FF",
        onBackground: "#191C20",
        surface: "#F8F9FF",
        onSurface: "#191C20",
        surfaceVariant: "#DFE2EB",
        onSurfaceVariant: "#43474E",
        outline: "#73777F",
        outlineVariant: "#C3C6CF",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#2E3035",
        inverseOnSurface: "#EFF0F7",
        inversePrimary: "#A4C9FE",
        primaryFixed: "#D4E3FF",
        onPrimaryFixed: "#001C39",
        primaryFixedDim: "#A4C9FE",
        onPrimaryFixedVariant: "#204876",
        secondaryFixed: "#A0F2DE",
        onSecondaryFixed: "#00201A",
        secondaryFixedDim: "#84D6C3",
        onSecondaryFixedVariant: "#005145",
        tertiaryFixed: "#EDDCFF",
        onTertiaryFixed: "#260E44",
        tertiaryFixedDim: "#D7BAFB",
        onTertiaryFixedVariant: "#533C72",
        surfaceDim: "#D9DAE0",
        surfaceBright: "#F8F9FF",
        surfaceContainerLowest: "#FFFFFF",
        surfaceContainerLow: "#F2F3FA",
        surfaceContainer: "#EDEDF4",
        surfaceContainerHigh: "#E7E8EE",
        surfaceContainerHighest: "#E1E2E9",
    }
}

const darkTheme = {
    colors: {
        primary: "#A4C9FE",
        surfaceTint: "#A4C9FE",
        onPrimary: "#00315D",
        primaryContainer: "#204876",
        onPrimaryContainer: "#D4E3FF",
        secondary: "#84D6C3",
        onSecondary: "#00382F",
        secondaryContainer: "#005145",
        onSecondaryContainer: "#A0F2DE",
        tertiary: "#D7BAFB",
        onTertiary: "#3B255A",
        tertiaryContainer: "#533C72",
        onTertiaryContainer: "#EDDCFF",
        error: "#FFB4AB",
        onError: "#690005",
        errorContainer: "#93000A",
        onErrorContainer: "#FFDAD6",
        background: "#111111",
        onBackground: "#E1E2E9",
        surface: "#1D2742",
        onSurface: "#E1E2E9",
        surfaceVariant: "#43474E",
        onSurfaceVariant: "#C3C6CF",
        outline: "#8D9199",
        outlineVariant: "#43474E",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#E1E2E9",
        inverseOnSurface: "#2E3035",
        inversePrimary: "#3B608F",
        primaryFixed: "#D4E3FF",
        onPrimaryFixed: "#001C39",
        primaryFixedDim: "#A4C9FE",
        onPrimaryFixedVariant: "#204876",
        secondaryFixed: "#A0F2DE",
        onSecondaryFixed: "#00201A",
        secondaryFixedDim: "#84D6C3",
        onSecondaryFixedVariant: "#005145",
        tertiaryFixed: "#EDDCFF",
        onTertiaryFixed: "#260E44",
        tertiaryFixedDim: "#D7BAFB",
        onTertiaryFixedVariant: "#533C72",
        surfaceDim: "#1D2742",
        surfaceBright: "#37393E",
        surfaceContainerLowest: "#0C0E13",
        surfaceContainerLow: "#191C20",
        surfaceContainer: "#1D2024",
        surfaceContainerHigh: "#272A2F",
        surfaceContainerHighest: "#32353A",
    }
}

const appThemes = {
    light: lightTheme,
    dark: darkTheme
}

export default appThemes